server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: content_route
          uri: lb://centent-center
          predicates:
            - Path=/shares/**,/admin/**,/test1/**
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://8.142.133.95:9411/
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always