spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
  application:
    name: adminserver
server:
  port: 8022
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always